### ISSUE TITLE
About loss

### ISSUE THREAD

**Issue by zlj199502** [huanglianghua/open-vot#2]
Hi!
你的代码工作很棒～我想请教你一个问题，你在训练的时候第一代的损失会是无穷大吗？

**Comment by huanglianghua** [comment]
@zlj199502 Hi, you could set a small value to `lr_mult_linear_bias`, e.g., 1e-3, or just use the more stable `bn` norm instead of the `linear` one.

I have encountered the `inf` loss before when I was training the SiamFC tracker with `linear` norm. The bug is not fixed, I will check it out later. Thanks.

**Comment by zlj199502** [comment]
@huanglianghua  Thank you for your reply. I already change the value according to what you said, but the loss is still Nan.
